- hosts: "lxc"
  tasks:
  - name : Add RTL 433
    apt:
      name: rtl-433
      state: present


  - name : launch rtl_433 at boot
    cron:
      name: "launch rtl_433 at boot"
      special_time: reboot
      job: 'rtl_433 -C si -F "influx://192.168.10.169:8086/write?db=rtl&p=rtl&u=rtl" -F "mqtt://192.168.10.169:1883,user=rtl,pass=rtl"'
      